app/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate

db = SQLAlchemy()

def create_app():
    app = Flask(__name__)
    #app.config.from_object('config.Config')

    #db.init_app(app)
    #migrate = Migrate(app, db)

    # views Blueprint
    from .views import views
    app.register_blueprint(views, url_prefix='/')

    # auth Blueprint
    from .auth import auth

    return app

app/auth.py
from flask import Blueprint, render_template

auth = Blueprint('auth', __name__, template_folder='templates')

app/views.py
from flask import Blueprint, render_template

views = Blueprint('views', __name__, template_folder='templates')

# Homepage
@views.route('/')
def home(): # called at localhost:5500/
    return render_template('base.html')

app/templates/base.html
<!-- Base HTML -->
<!DOCTYPE html>
<html lang="en">


<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Truc's</title>
    <link rel="stylesheet" href="../static/css/style.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Ubuntu:ital,wght@0,300;0,400;0,500;0,700;1,300;1,400;1,500;1,700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">
</head>


<body>
    <nav id="desktop-nav">
        <div class="logo">
            <a href="{{ url_for('views.home') }}">
                TRUC'S
            </a>
        </div>

        <div>
            <ul class="nav-links">
                <li><a href="#shop">SHOP</a></li>
                <li><a href="#about">ABOUT US</a></li>
                <li><a href="#contact">CONTACT US</a></li>
            </ul>
        </div>
    </nav>


</body>